### Numpy
- 데이터는 행렬로 표현
- 행열 데이터 생성, 수정, 계산 등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란로 작성(파이썬으로 작성하지만 내부적으로 이렇게 속도빠름)
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [1]:
import numpy as np

In [3]:
#행렬 데이터 생성 
# ndarray: 한가지 데이터 타입만 값으로 사용이 가능
array=np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [6]:
array2=np.array(
   [[1,2,3],
    [4,5,6]]
)
array2, array2.ndim, array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [10]:
# 행렬의 모양(shape) 변경
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
#행렬 데이터의 선택 : offset index : masking
array2[1][:2]

#array2[1, 2]랑 array2[1][2] 같음

array([4, 5])

In [18]:
#데이터 수정
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array2[1][2]=10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [22]:
#브로드 캐스팅
array2[0]=0 #스칼라 값 넣어주면 모든 값에 넣어줌
array2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [23]:
array2[0]=[7,8,9]
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [26]:
#조건으로 선택
idx =array2 > 7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [28]:
array2[idx] #True인 데이터만 남기고 필터링

array([ 8,  9, 10])

In [29]:
array2[idx]=100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [30]:
#행렬 데이터의 생성 2

In [33]:
data=np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
data.dtype

dtype('float64')

In [37]:
data2=data.astype("int")
data2.dtype

dtype('int32')

In [40]:
data=np.ones((2,3))
data

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [44]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [45]:
np.arange(5,10,2)

array([5, 7, 9])