### 1. linspace, logspace
- linspace:범위에서 선형적으로 분할할 위치의값 출력
- logspce

In [2]:
import numpy as np
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [3]:
#log10(x1)=2,log10(x2)=3,log10(x3)=4
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [7]:
# 30세에 연봉이 $100000이고 60세의 연봉이 $1000000일때
# 연봉이 선형, 지수로 증가하는 두 경우에서 40세,50세 연봉출력

age_30=100000
age_60=1000000
np.linspace(age_30,age_60,4)

array([ 100000.,  400000.,  700000., 1000000.])

In [9]:
np.logspace(np.log10(age_30),np.log10(age_60),4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤값을 설정값
- rand : 균등분포로 난수 생성(뽑힐확률동일)
- randn : 정규분포로 난수 발생
- randint : 균등분포로 정수값 발생
- shuffle : 행렬데이터 섞어줌
- choice : 특정 확률로 데이터 선택

In [14]:
#seed
np.random.seed(1)
result1=np.random.randint(10,100,10)

np.random.seed(1)
result2=np.random.randint(10,100,10)

np.random.seed(2)
result3=np.random.randint(10,100,10)

result1,result2,result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [17]:
#0~1사이를 균등하게 나누어 뽑힐확률 같게해서 뽑음
np.random.rand(10)

array([0.18626021, 0.34556073, 0.39676747, 0.53881673, 0.41919451,
       0.6852195 , 0.20445225, 0.87811744, 0.02738759, 0.67046751])

In [19]:
#정규분포따르게 0에 가까울수록 뽑힐 확률이 크다
np.random.randn(10)

array([-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
       -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547])

In [28]:
#shuffle
r=np.random.randint(1,10,(3,4))
r

array([[7, 5, 6, 7],
       [3, 6, 8, 9],
       [5, 5, 8, 8]])

In [29]:
#가장 바깥 차원만 shuffle됨
np.random.shuffle(r)
r

array([[5, 5, 8, 8],
       [7, 5, 6, 7],
       [3, 6, 8, 9]])

In [33]:
#choice - p를 다 더했을 때 1이되게
np.random.choice(5,10,p=[0.1,0,0.4,0.2,0.3])

array([2, 4, 3, 0, 4, 3, 4, 2, 2, 4])

In [36]:
#unique
numbers,counts=np.unique(r,return_counts=True)
print(numbers)
print(counts)

[3 5 6 7 8 9]
[1 3 2 2 3 1]


### 3. 행렬 데이터의 결합
- concatenate


In [38]:
na1=np.random.randint(10,size=(2,3))
na2=np.random.randint(10,size=(3,2))
na3=np.random.randint(10,size=(3,3))

In [42]:
print(na1)
print(na2)
print(na3)

[[4 4 6]
 [8 8 9]]
[[2 7]
 [5 5]
 [4 5]]
[[8 5 8]
 [1 1 8]
 [7 0 3]]


In [39]:
#세로결합
np.concatenate((na1,na3))

array([[4, 4, 6],
       [8, 8, 9],
       [8, 5, 8],
       [1, 1, 8],
       [7, 0, 3]])

In [44]:
#가로결합
np.concatenate((na2,na3),axis=1)

array([[2, 7, 8, 5, 8],
       [5, 5, 1, 1, 8],
       [4, 5, 7, 0, 3]])

In [46]:
# c_,r_
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
np.r_[np.array([1,2,3]),np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [48]:
# split,var,std,mean ...